name: real-estate

dependencies:
- python>=3.9.0
- pip
- pandas
- plotly
- numpy
- ipykernel
- pip:
  - pycaret
  - alpha-vantage
  - datetime
  - nbformat
  - uszipcode
  - pandera
  - streamlit
  - scikit-learn
